# Generated by Django 4.1.5 on 2023-01-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
